from spaceone.inventory_v2.manager.asset_manager import AssetManager
from spaceone.inventory_v2.manager.asset_type_manager import AssetTypeManager
from spaceone.inventory_v2.manager.collector_rule_manager import CollectorRuleManager
from spaceone.inventory_v2.manager.region_manager import RegionManager
from spaceone.inventory_v2.manager.collecting_manager import CollectingManager
from spaceone.inventory_v2.manager.namespace_group_manager import NamespaceGroupManager
from spaceone.inventory_v2.manager.namespace_manager import NamespaceManager
