from spaceone.inventory_v2.service.asset_service import AssetService
from spaceone.inventory_v2.service.asset_type_service import AssetTypeService
from spaceone.inventory_v2.service.collector_rule_service import CollectorRuleService
from spaceone.inventory_v2.service.region_service import RegionService
from spaceone.inventory_v2.service.namespace_group_service import NamespaceGroupService
from spaceone.inventory_v2.service.namespace_service import NamespaceService
