from spaceone.inventory_v2.service.asset_service import AssetService
from spaceone.inventory_v2.service.asset_type_service import AssetTypeService
from spaceone.inventory_v2.service.region_service import RegionService
